### ISSUE TITLE
Server side instability

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#283]
Today between 02:16 and 02:42 (UTC) server was unstable.

In my scenario I have several clients that are always on and connected to server.

During the period mentioned above all clients kept being disconnected from server. Then reconnected back and so on.
Below are logs from a disconnect-connect moment seen from both server and client side.

1. Could you please tell me why happened? 
2. What can I do avoid this?

Hub names are not the real ones. If needed I can provide them.

**Server side** log look like this:

```2018-11-30 02:16:39.966 +00:00 [Verbose]Sent a ping message to the client. { EventId: { Id: 3, Name: "SentPing" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionContext" }
2018-11-30 02:16:39.966 +00:00 [Verbose]Sent a ping message to the client. { EventId: { Id: 3, Name: "SentPing" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionContext" }
2018-11-30 02:16:42.043 +00:00 [Error]Connection "ea647d03-236c-4f5f-94f4-8b462f42d8d2" to the service was dropped. { EventId: { Id: 4, Name: "ConnectionDropped" }, SourceContext: "Microsoft.Azure.SignalR.ServiceConnection" }
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
2018-11-30 02:16:42.053 +00:00 [Error]Connection "3b5ee61b-5f0d-4754-9a86-9e601fe7a354" to the service was dropped. { EventId: { Id: 4, Name: "ConnectionDropped" }, SourceContext: "Microsoft.Azure.SignalR.ServiceConnection" }
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
2018-11-30 02:16:42.070 +00:00 [Information]Transport is stopping. { EventId: { Id: 6, Name: "TransportStopping" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.071 +00:00 [Information]HttpConnection Disposed. { EventId: { Id: 6, Name: "Disposed" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.072 +00:00 [Information]Starting transport. Transfer mode: Binary. Url: 'wss://myhub.service.signalr.net/server/?hub=clienthub&cid=3b5ee61b-5f0d-4754-9a86-9e601fe7a354'. { EventId: { Id: 1, Name: "StartTransport" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.082 +00:00 [Error]Connection "c4c606cb-b917-4fe7-ad29-cd43fc5d62f7" to the service was dropped. { EventId: { Id: 4, Name: "ConnectionDropped" }, SourceContext: "Microsoft.Azure.SignalR.ServiceConnection" }
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
2018-11-30 02:16:42.091 +00:00 [Information]Transport is stopping. { EventId: { Id: 6, Name: "TransportStopping" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.092 +00:00 [Information]HttpConnection Disposed. { EventId: { Id: 6, Name: "Disposed" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.100 +00:00 [Error]Connection "178d14da-5360-4afd-8361-6983c4f77278" to the service was dropped. { EventId: { Id: 4, Name: "ConnectionDropped" }, SourceContext: "Microsoft.Azure.SignalR.ServiceConnection" }
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
2018-11-30 02:16:42.111 +00:00 [Information]Transport is stopping. { EventId: { Id: 6, Name: "TransportStopping" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.111 +00:00 [Information]HttpConnection Disposed. { EventId: { Id: 6, Name: "Disposed" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.112 +00:00 [Information]Starting transport. Transfer mode: Binary. Url: 'wss://myhub.service.signalr.net/server/?hub=webuihub&cid=178d14da-5360-4afd-8361-6983c4f77278'. { EventId: { Id: 1, Name: "StartTransport" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.121 +00:00 [Error]Connection "de868e38-f754-4d2f-9fe1-e777292a738f" to the service was dropped. { EventId: { Id: 4, Name: "ConnectionDropped" }, SourceContext: "Microsoft.Azure.SignalR.ServiceConnection" }
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.Azure.SignalR.ServiceConnectionBase.ProcessIncomingAsync()
2018-11-30 02:16:42.102 +00:00 [Information]Transport is stopping. { EventId: { Id: 6, Name: "TransportStopping" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.130 +00:00 [Information]HttpConnection Disposed. { EventId: { Id: 6, Name: "Disposed" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.131 +00:00 [Information]Starting transport. Transfer mode: Binary. Url: 'wss://myhub.service.signalr.net/server/?hub=webuihub&cid=ea647d03-236c-4f5f-94f4-8b462f42d8d2'. { EventId: { Id: 1, Name: "StartTransport" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.132 +00:00 [Information]Transport is stopping. { EventId: { Id: 6, Name: "TransportStopping" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.139 +00:00 [Information]HttpConnection Disposed. { EventId: { Id: 6, Name: "Disposed" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.140 +00:00 [Information]Starting transport. Transfer mode: Binary. Url: 'wss://myhub.service.signalr.net/server/?hub=clienthub&cid=de868e38-f754-4d2f-9fe1-e777292a738f'. { EventId: { Id: 1, Name: "StartTransport" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.139 +00:00 [Error]Error while sending message to the service. { EventId: { Id: 6, Name: "ErrorSendingMessage" }, SourceContext: "Microsoft.Azure.SignalR.ServiceConnection" }
System.InvalidOperationException: The connection is not active, data cannot be sent to the service.
   at Microsoft.Azure.SignalR.ServiceConnectionBase.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceConnection.ProcessOutgoingMessagesAsync(ServiceConnectionContext connection)
2018-11-30 02:16:42.160 +00:00 [Information]HttpConnection Started. { EventId: { Id: 3, Name: "Started" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.161 +00:00 [Information]HttpConnection Started. { EventId: { Id: 3, Name: "Started" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.169 +00:00 [Information]HttpConnection Started. { EventId: { Id: 3, Name: "Started" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.169 +00:00 [Information]HttpConnection Started. { EventId: { Id: 3, Name: "Started" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:42.211 +00:00 [Debug]OnConnectedAsync ending. { EventId: { Id: 6, Name: "ConnectedEnding" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionHandler" }
2018-11-30 02:16:42.214 +00:00 [Information]Starting transport. Transfer mode: Binary. Url: 'wss://myhub.service.signalr.net/server/?hub=clienthub&cid=c4c606cb-b917-4fe7-ad29-cd43fc5d62f7'. { EventId: { Id: 1, Name: "StartTransport" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport" }
2018-11-30 02:16:42.235 +00:00 [Information]HttpConnection Started. { EventId: { Id: 3, Name: "Started" }, SourceContext: "Microsoft.AspNetCore.Http.Connections.Client.HttpConnection" }
2018-11-30 02:16:44.009 +00:00 [Debug]OnConnectedAsync started. { EventId: { Id: 5, Name: "ConnectedStarting" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionHandler" }
2018-11-30 02:16:44.010 +00:00 [Debug]Found protocol implementation for requested protocol: "json". { EventId: { Id: 2, Name: "FoundImplementationForProtocol" }, SourceContext: "Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver" }
2018-11-30 02:16:44.011 +00:00 [Information]Completed connection handshake. Using HubProtocol '"json"'. { EventId: { Id: 1, Name: "HandshakeComplete" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionContext" }
2018-11-30 02:16:44.970 +00:00 [Debug]Received hub invocation: "InvocationMessage { InvocationId: \"1\", Target: \"clientId\", Arguments: [ myName, 5d8d61932f48204eac93c5e2ac9bcd4d1f14faa0640c9d73d067d63f7319ec3d, 0, 11/30/2018 1:01:21 AM, 11/30/2018 2:16:44 AM ] }". { EventId: { Id: 1, Name: "ReceivedHubInvocation" }, SourceContext: "Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher" }
2018-11-30 02:16:45.136 +00:00 [Verbose]InvocationId "1": Sending result of type '"System.Void"'. { EventId: { Id: 7, Name: "SendingResult" }, SourceContext: "Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher" }
2018-11-30 02:16:48.969 +00:00 [Verbose]Sent a ping message to the client. { EventId: { Id: 3, Name: "SentPing" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionContext" }
```

**Client side** logs look like this:
```
2018-11-30 04:16:41.528 +02:00 [Verbose] Acquired the Connection Lock in order to ping the server.
2018-11-30 04:16:41.529 +02:00 [Debug] Sending "PingMessage" message.
2018-11-30 04:16:41.530 +02:00 [Debug] Sending "PingMessage" message completed.
2018-11-30 04:16:41.531 +02:00 [Verbose] Releasing Connection Lock in "PingServer" ("/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs":956).
2018-11-30 04:16:42.778 +02:00 [Error] The server connection was terminated with an error.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Exception: Exception from HRESULT: 0x80072EFE
   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WinRTWebSocket.<ReceiveAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.<StartReceiving>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<ReceiveLoop>d__62.MoveNext()
2018-11-30 04:16:42.894 +02:00 [Verbose] Waiting on Connection Lock in "ReceiveLoop" ("/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs":840).
2018-11-30 04:16:42.895 +02:00 [Verbose] Releasing Connection Lock in "ReceiveLoop" ("/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs":849).
2018-11-30 04:16:42.928 +02:00 [Information] Transport is stopping.
2018-11-30 04:16:42.933 +02:00 [Information] HttpConnection Disposed.
2018-11-30 04:16:42.953 +02:00 [Debug] Canceling all outstanding invocations.
2018-11-30 04:16:42.989 +02:00 [Error] Connection is shutting down due to an error.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Exception: Exception from HRESULT: 0x80072EFE
   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WinRTWebSocket.<ReceiveAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.<StartReceiving>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<ReceiveLoop>d__62.MoveNext()
2018-11-30 04:16:43.100 +02:00 [Debug] Invoking the Closed event handler.
2018-11-30 04:16:43.105 +02:00 [Debug] >>> CONNECTION CLOSED
2018-11-30 04:16:43.109 +02:00 [Error] HubConnection_Closed Exception
2018-11-30 04:16:43.114 +02:00 [Debug] Thread: 15 - Hash: 26228946  - 11/30/2018 4:16:43 AM - Connecting...
2018-11-30 04:16:43.115 +02:00 [Verbose] Waiting on Connection Lock in "StartAsyncCore" ("/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs":289).
2018-11-30 04:16:43.116 +02:00 [Debug] Starting HubConnection.
2018-11-30 04:16:43.665 +02:00 [Information] Starting transport. Transfer mode: Text. Url: 'wss://myhub.service.signalr.net/client/?hub=clienthub&asrs.op=%2FhubName&username=user&systemId=system&id=cVdRR3HGB9bmpPX1RVgQKQ'.
2018-11-30 04:16:43.994 +02:00 [Information] HttpConnection Started.
2018-11-30 04:16:43.995 +02:00 [Information] Using HubProtocol '"json" v1'.
2018-11-30 04:16:43.996 +02:00 [Debug] Sending Hub Handshake.
2018-11-30 04:16:44.066 +02:00 [Debug] Handshake with server complete.
2018-11-30 04:16:44.067 +02:00 [Debug] Receive loop starting.
2018-11-30 04:16:44.068 +02:00 [Debug] Sending "PingMessage" message.
2018-11-30 04:16:44.069 +02:00 [Debug] Sending "PingMessage" message completed.
2018-11-30 04:16:44.071 +02:00 [Information] HubConnection started.
2018-11-30 04:16:44.072 +02:00 [Verbose] Releasing Connection Lock in "StartAsyncCore" ("/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs":333).
2018-11-30 04:16:44.073 +02:00 [Debug] Thread: 10 - Hash: 26228946  -  11/30/2018 4:16:44 AM - Connected 
2018-11-30 04:16:44.215 +02:00 [Verbose] Waiting on Connection Lock in "InvokeCoreAsyncCore" ("/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs":445).
2018-11-30 04:16:44.216 +02:00 [Verbose] Invocation "1" created.
2018-11-30 04:16:44.218 +02:00 [Verbose] Preparing blocking invocation '"1"' of '"clientId"', with return type '"System.Object"' and 5 argument(s).
2018-11-30 04:16:44.219 +02:00 [Debug] Registering Invocation ID '"1"' for tracking.
2018-11-30 04:16:44.221 +02:00 [Verbose] Issuing Invocation '"1"': "System.Object" "clientId"("System.String, System.String, System.Int64, System.DateTime, System.DateTime").
2018-11-30 04:16:44.222 +02:00 [Debug] Sending "InvocationMessage" message '"1"'.
2018-11-30 04:16:44.224 +02:00 [Debug] Sending "InvocationMessage" message '"1"' completed.
2018-11-30 04:16:44.225 +02:00 [Verbose] Releasing Connection Lock in "InvokeCoreAsyncCore" ("/_/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs":458).
2018-11-30 04:16:44.227 +02:00 [Debug] >>> CONNECTED!
2018-11-30 04:16:45.191 +02:00 [Debug] Processing 44 byte message from server.
2018-11-30 04:16:45.192 +02:00 [Verbose] Resetting keep-alive timer, received a message from the server.
2018-11-30 04:16:45.193 +02:00 [Verbose] Received Completion for Invocation "1".
2018-11-30 04:16:45.194 +02:00 [Verbose] Invocation "1" marked as completed.
2018-11-30 04:16:45.196 +02:00 [Verbose] Invocation "1" disposed.
2018-11-30 04:16:49.023 +02:00 [Debug] Processing 11 byte message from server.
2018-11-30 04:16:49.025 +02:00 [Verbose] Resetting keep-alive timer, received a message from the server.
2018-11-30 04:16:49.027 +02:00 [Verbose] Received a ping message.
2018-11-30 04:16:49.061 +02:00 [Verbose] Acquired the Connection Lock in order to ping the server.
2018-11-30 04:16:49.063 +02:00 [Debug] Sending "PingMessage" message.
2018-11-30 04:16:49.064 +02:00 [Debug] Sending "PingMessage" message completed.
```

**Comment by vicancy** [comment]
Thanks for providing the detailed trace. Could you email me `lianwei<at>microsoft.com` (`<at>` to `@`) your instance name and region? I will take a look at the service side log to see what happend.

**Comment by vicancy** [comment]
Before the error took place, is there any logs like `Service timeout. 30.00ms elapsed without receiving a message from service.` from the app server side?

**Comment by alexiordan** [comment]
No, there is no "`Service timeout. 30.00ms elapsed without receiving a message from service.`" all day.
Not even a "`timeout`"  ...
I looked in the same log file from where I took the server side log above.

**Comment by vicancy** [comment]
According to the service side log, the 7-layer load balancer experienced several configuration reload which caused the load balancer to restart, as a result, the persistent connections through the load balancer were dropped. We are investigating the root cause for the config change, will get you updated once we have progress.

From application’s perspective, it is possible that persistent connections experience disconnect, due to, e.g., service deployment, or network issues. So it is suggested to have **reconnect** logic in the client side.

**Comment by alexiordan** [comment]
1. Thank you for your client side reconnect advise.
I already have such logic in place:
``` 2018-11-30 04:16:43.116 +02:00 [Debug] Starting HubConnection. ``` is the result of it. 

2. I'll wait then for updates on the root cause.

3. On the other hand such things are supposed to happen? 
I'm not talking about one seldom disconnect (let's say once a day), but this kind of instability for almost half an hour.

**Comment by vicancy** [comment]
We plan to fix it in next service update cycle, which will start roll out in 12/17 and take effect to all the regions on 12/21 . Is the time frame OK for you?

**Comment by torhovland** [comment]
Hi, @vicancy!

We are connecting to Azure SignalR Service from an Azure Web App as well as from an Azure Function App. We are getting a lot of exceptions as shown below. Is this the kind of issue that should have been fixed by the deployment on 12/21? Has the fix been delayed?

```
[{"parsedStack":[
    {"assembly":"System.Net.WebSockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.WebSockets.ManagedWebSocket+<ReceiveAsyncPrivate>d__65`2.MoveNext","level":0,"line":0},
    {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":1,"line":0},
    {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":2,"line":0},
    {"assembly":"Microsoft.AspNetCore.Http.Connections.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport+<StartReceiving>d__19.MoveNext","level":3,"line":0},
    {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":4,"line":0},
    {"assembly":"System.IO.Pipelines, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51","method":"System.IO.Pipelines.PipeCompletion.ThrowLatchedException","level":5,"line":0},
    {"assembly":"System.IO.Pipelines, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51","method":"System.IO.Pipelines.Pipe.GetReadResult","level":6,"line":0},
    {"assembly":"System.IO.Pipelines, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51","method":"System.IO.Pipelines.Pipe.GetReadAsyncResult","level":7,"line":0},
    {"assembly":"System.IO.Pipelines, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51","method":"System.IO.Pipelines.Pipe+DefaultPipeReader.GetResult","level":8,"line":0},
    {"assembly":"Microsoft.Azure.SignalR.Common, Version=1.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Azure.SignalR.ServiceConnectionBase+<ProcessIncomingAsync>d__39.MoveNext","level":9,"line":0}],"severityLevel":"Error","outerId":"0","message":"Connection 00000000-1c7b-4ca5-8d6a-5b8c9bbed668 to the service was dropped.","type":"System.Net.WebSockets.WebSocketException","id":"44180650"},
    {"parsedStack":[
        {"assembly":"System.Net.WebSockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected","level":0,"line":0},
        {"assembly":"System.Net.WebSockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.WebSockets.ManagedWebSocket+<EnsureBufferContainsAsync>d__75.MoveNext","level":1,"line":0},
        {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":2,"line":0},
        {"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":3,"line":0},
        {"assembly":"System.Net.WebSockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Net.WebSockets.ManagedWebSocket+<ReceiveAsyncPrivate>d__65`2.MoveNext","level":4,"line":0}],"severityLevel":"Error","outerId":"44180650","message":"The remote party closed the WebSocket connection without completing the close handshake.","type":"System.Net.WebSockets.WebSocketException","id":"22174184"}]
```

**Comment by vicancy** [comment]
Hi @torhovland does the error persist or did it recover very soon? What is the time frame when the error took place. There are some cases when the connections can drop such as when deployment took place or network issues or internal errors. We have reconnect logic from the server SDK side so the issues are expected to be recovered automatically.

**Comment by torhovland** [comment]
@vicancy We are getting quite a few of these, i.e. about 200 over the last 7 days, on a development environment with little usage. They can happen anytime during the day or night, sometimes once every hour, sometimes with many hours in between. It always seems to be the same 5 connection IDs that are dropped. We do not run deployments as often as this. The Web App is set to Always On. The Function App is deployed to a Consumption Plan. Would you recommend running it on a dedicated App Service Plan instead? I'm considering filtering out these exception messages from our Application Insights logging if you think there is nothing we can do about them on our end.

**Comment by vicancy** [comment]
@torhovland thanks for the info, it is probably caused by the same load balancer issue. We did a hot fix for @alexiordan's case. (The normal service update was frozen for holiday season). Could you email me(`lianwei@microsoft.com`) your resource name so that we can do a hot fix for you?

**Comment by jsheetzati** [comment]
Just curious, has this hotfix been deployed?

**Comment by vicancy** [comment]
@jsheetzati Yes it has. All the current Azure instance should be updated.

**Comment by jsheetzati** [comment]
We are seeing some very inconsistent connection issues. In our beta environment, connections continually connect and disconnect immediately, whereas our staging environment, may take up to 5 disconnects/reconnects before it establishes the connection. Our test environment works fine 100% of the time, and we do not seem to be having issues over there..

Are you able to look at our logs if I email you our resource names? This seemed to come out of nowhere for us. We tried resetting the App Service running the hub as well as the managed SignalR.

**Comment by vicancy** [comment]
@jsheetzati You can open a ticket and our support will contact you soon. If they are not able to solve the issue, the issue will be transfered to us. 

Of course you can also email me the issue directly.
In the email, please provide the following info for us to identify the issue efficiently: 
1. the instance name of your Azure SignalR 
2. the time range of the issue, 
3. the logs from the server side including the info logs and exception logs, 
4. If the issue happens from client side, a [HAR file](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366) is appreciated.

**Comment by alexiordan** [comment]
@vicancy, 
I am again experiencing some disfunctionalities right now.
Clients got disconnected and even if they retry to connect, they do not succed.
They are still offline now!

Server side only states:
```
2019-01-31 05:54:34.014 +00:00 [Debug]OnConnectedAsync ending. { EventId: { Id: 6, Name: "ConnectedEnding" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionHandler" }
2019-01-31 05:54:34.059 +00:00 [Debug]OnConnectedAsync ending. { EventId: { Id: 6, Name: "ConnectedEnding" }, SourceContext: "Microsoft.AspNetCore.SignalR.HubConnectionHandler" }
```
Client side (please note, that they are in descending order by date):
```
Failed to start connection. Error getting negotiation response from 'https://myhub.service.signalr.net:5001/client/?hub=myhub&asrs.op=%2Fupdater&username=myClient&systemId=myClient'.	2019-01-31T05:55:26.208	
OnConnectionExceptionAsync: Exception: An error occurred while sending the request.	2019-01-31T05:55:11.069	
>>> CONNECTION EXCEPTION	2019-01-31T05:55:11.068	
Failed to start connection. Error getting negotiation response from 'https://myhub.service.signalr.net:5001/client/?hub=myhub&asrs.op=%2Fupdater&username=myClient&systemId=myClient'.	2019-01-31T05:55:11.046	
Retry no: 2. Waiting 4049 seconds before retrying.	2019-01-31T05:54:59.530	
>>> CONNECTION EXCEPTION	2019-01-31T05:54:59.529	
OnConnectionExceptionAsync: Exception: An error occurred while sending the request.	2019-01-31T05:54:59.529	
Failed to start connection. Error getting negotiation response from 'https://myhub.service.signalr.net:5001/client/?hub=myhub&asrs.op=%2Fupdater&username=myClient&systemId=myClient'.	2019-01-31T05:54:59.485	
Retry no: 1. Waiting 3021 seconds before retrying.	2019-01-31T05:54:49.375	
OnConnectionExceptionAsync: Exception: An error occurred while sending the request.	2019-01-31T05:54:49.366	
>>> CONNECTION EXCEPTION	2019-01-31T05:54:49.365	
Failed to start connection. Error getting negotiation response from 'https://myhub.service.signalr.net:5001/client/?hub=myhub&asrs.op=%2Fupdater&username=myClient&systemId=myClient'.	2019-01-31T05:54:49.324	
HubConnection_Closed Exception	2019-01-31T05:54:34.911	
>>> CONNECTION CLOSED	2019-01-31T05:54:34.910	
Connection is shutting down due to an error.	2019-01-31T05:54:34.843	
Error: Server timeout (10000.00ms) elapsed without receiving a message from the server.	2019-01-31T05:54:34.374	
Error: Server timeout (10000.00ms) elapsed without receiving a message from the server.	2019-01-31T05:54:34.372	
Error: Server timeout (10000.00ms) elapsed without receiving a message from the server.	2019-01-31T05:54:34.370	
Error: Server timeout (10000.00ms) elapsed without receiving a message from the server.	2019-01-31T05:54:34.354	
Error: Server timeout (10000.00ms) elapsed without receiving a message from the server. 2019-01-31T05:54:34.348
```

I have replaced some identification information from connection URL. The subscription is the same as for the initial post. Would you please tell me why is this happening?

**Comment by vicancy** [comment]
@alexiordan 5001 port is obsoleted and is now disabled, please use the updated connection string from the portal in your server side code, or update to the latest SDK, as tracked in this issue: https://github.com/Azure/azure-signalr/issues/123

**Comment by alexiordan** [comment]
@vicancy, I am using the 1.0.5 SignalRService SDK in my appservice...

**Comment by alexiordan** [comment]
So it worked! 
I had to restart the client, but it worked. Sorry for for disturbing.

**Comment by vicancy** [comment]
Close the issue as it should be fixed.
