### ISSUE TITLE
Microsoft.Azure.SignalR.Management.ServiceHubContext does not reconnect with ServiceTransportType.Persistent

### ISSUE THREAD

**Issue by scale-tone** [Azure/azure-signalr#627]
Sample project is [here](https://github.com/scale-tone/AzureSignalRTest).

Steps to reproduce:
1. Get the [sources](https://github.com/scale-tone/AzureSignalRTest).
2. Put your Azure SignalR Service Connection String to [both](https://github.com/scale-tone/AzureSignalRTest/blob/master/AzureSignalRConsoleTest/appsettings.json) [appsettings.json](https://github.com/scale-tone/AzureSignalRTest/blob/master/AzureSignalRWebTest/appsettings.json) files.
3. Run both web and console apps locally.
4. Press Enter in console app window and observe messages from console app appearing on the web app page.
5. Go into airplane mode.
6. Wait ~10 seconds.
7. Press Enter in console app a couple of times. Note that it doesn't throw.
8. Wait ~10 seconds.
9. Turn airplane mode off.
10. Refresh the web app page (to make the client JavaScript reconnect to Azure SignalR).
11. Press Enter in console app window several times more. Note that again it keeps succeeding.

Expected behavior: messages continue arriving on the web app's page.

Actual behavior: no new messages arrive. The console app's connection gets silently dropped and is never reestablished again. While SendCoreAsync() method keeps succeeding, thus sending messages to /dev/null.

I can also see a [similar issue reported previously](https://github.com/Azure/azure-signalr/issues/485), which is likely to be caused by this bug.

**Comment by realwanpengli** [comment]
Hi @scale-tone , it is a bug that will be fixed in this [pull request](https://github.com/Azure/azure-signalr/pull/630).

There's a dead lock issue. In your code, there's a infinite loop right after the `CreateServiceHubContextAsync`, `CreateServiceHubContextAsync` waits the server connection to complete initialization, but server connection initialization waits the infinite loop finish, which causes the dead lock. It causes the server connection initialization never completes.

**Comment by scale-tone** [comment]
@realwanpengli , any news on this?

**Comment by realwanpengli** [comment]
@scale-tone already fixed in #707 , should be public in next release.

**Comment by arek-avanade** [comment]
Is this issue actually fixed? Can someone confirm?

**Comment by scale-tone** [comment]
@arek-avanade , tried the above sample with latest Microsoft.Azure.SignalR.Management 1.7.0 

hubContext.Clients.All.SendCoreAsync() method still doesn't throw when disconnected (not sure whether it was intended or not), but after restoring connectivity it does reconnects and is capable of sending messages again.

**Comment by vicancy** [comment]
Should be resolved.
